apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::886436961042:role/eks-cluster-admin
      username: eks-cluster-admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::886436961042:user/eks-admin
      username: eks-admin
      groups:
        - system:masters
mapUsers: |
    - userarn: arn:aws:iam::886436961042:role/eks-admin-role
      role: eks-admin
      groups:
        - system:masters
mapUsers: |
    - userarn: arn:aws:iam::886436961042:role/EKSAdminRole
      role: EKSAdminRole
      groups:
        - system:masters

