apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-web
  namespace: python-web
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: python-web-ingress
spec:
  rules:
    - host: python-web.example.com  # Replace with your domain or remove if not using host-based routing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-web
                port:
                  number: 80
