apiVersion: v1
kind: Service
metadata:
  name: python-web
  namespace: python-web
spec:
  selector:
    app: python-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Change this if needed (valid range: 30000-32767)
